version = 0.1
[default.deploy.parameters]
stack_name = "sam-stack"
resolve_s3 = true
s3_prefix = "sam-stack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
